Repository Yash-Garg/qBittorrent-Manager, pull requests merged in 2022-10, with the labels that each got.

#97 tests: add more tests in `ViewModels`
  .github/workflows/pr_ci.yml
  app/build.gradle.kts
  app/src/androidTest/kotlin/dev/yashgarg/qbit/CustomTestRunner.kt
  app/src/androidTest/kotlin/dev/yashgarg/qbit/ui/config/ConfigViewModelTest.kt
  app/src/androidTest/kotlin/dev/yashgarg/qbit/ui/version/VersionViewModelTest.kt
  app/src/main/kotlin/dev/yashgarg/qbit/data/manager/ClientManager.kt
  gradle/libs.versions.toml
Labels: enhancement, hacktoberfest, PR: unreviewed

#103 workflow: add androidTests emulator actions step
  .github/workflows/pr_ci.yml
  app/build.gradle.kts
  app/src/androidTest/kotlin/dev/yashgarg/qbit/ui/config/ConfigViewModelTest.kt
Labels: PR: unreviewed

#104 add unit tests to Config and Version ViewModels
  .github/workflows/pr_ci.yml
  app/build.gradle.kts
  app/src/androidTest/kotlin/dev/yashgarg/qbit/CustomTestRunner.kt
  app/src/androidTest/kotlin/dev/yashgarg/qbit/ui/config/ConfigViewModelTest.kt
  app/src/main/kotlin/dev/yashgarg/qbit/data/manager/ClientManager.kt
  app/src/main/kotlin/dev/yashgarg/qbit/di/AppModule.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModel.kt
  app/src/test/kotlin/dev/yashgarg/qbit/FakeClientManager.kt
  app/src/test/kotlin/dev/yashgarg/qbit/MainCoroutineRule.kt
  app/src/test/kotlin/dev/yashgarg/qbit/ui/config/ConfigViewModelTest.kt
  app/src/test/kotlin/dev/yashgarg/qbit/ui/version/VersionViewModelTest.kt
  gradle/libs.versions.toml
Labels: enhancement, hacktoberfest, PR: unreviewed, PR: draft, hacktoberfest-accepted

#105 test: add tests for `ServerViewModel`
  app/src/main/kotlin/dev/yashgarg/qbit/di/AppModule.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModel.kt
  app/src/test/kotlin/dev/yashgarg/qbit/Constants.kt
  app/src/test/kotlin/dev/yashgarg/qbit/MainDispatcherRule.kt
  app/src/test/kotlin/dev/yashgarg/qbit/ui/config/ConfigViewModelTest.kt
  app/src/test/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModelTest.kt
  app/src/test/kotlin/dev/yashgarg/qbit/ui/version/VersionViewModelTest.kt
Labels: enhancement, hacktoberfest, PR: draft, hacktoberfest-accepted

#110 workflow: add matrix for all action steps
  .github/workflows/pr_ci.yml
Labels: enhancement, hacktoberfest, PR: reviewed-approved, hacktoberfest-accepted

#115 [QBIT-25] Add notification channels for pushing status updates
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/dev/yashgarg/qbit/MainActivity.kt
  app/src/main/kotlin/dev/yashgarg/qbit/QbitApplication.kt
  app/src/main/kotlin/dev/yashgarg/qbit/data/manager/ClientManager.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/common/ListTileTextView.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/config/ConfigFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/adapter/TorrentListAdapter.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/tabs/TorrentFilesFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/tabs/TorrentInfoFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/tabs/TorrentPeersFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/utils/ClipboardUtil.kt
  app/src/main/kotlin/dev/yashgarg/qbit/worker/StatusWorker.kt
  app/src/main/res/drawable/baseline_sync.xml
  app/src/main/res/layout/list_tile.xml
  app/src/main/res/layout/torrent_details_fragment.xml
  app/src/main/res/values/styles.xml
  common/build.gradle.kts
  common/src/main/kotlin/dev/yashgarg/qbit/notifications/AppNotificationManager.kt
  common/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  ui-compose/src/main/kotlin/dev/yashgarg/qbit/ui/compose/TorrentContentTreeView.kt
  ui-compose/src/main/kotlin/dev/yashgarg/qbit/ui/compose/theme/Color.kt
  ui-compose/src/main/kotlin/dev/yashgarg/qbit/ui/compose/theme/Type.kt
Labels: PR: unreviewed

#118 [QBIT-34] Add an app icon with a monochrome layer for A12+
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement, PR: unreviewed

#120 Add gradle build scan to publish always
  settings.gradle.kts
Labels: PR: unreviewed

#123 [QBIT-35] Allow app rotation and add a check for `savedInstanceState`
  app/src/main/kotlin/dev/yashgarg/qbit/MainActivity.kt
Labels: enhancement, PR: unreviewed

#129 refactor: switch app name
  README.md
  common/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: PR: unreviewed

#130 chore: add new mockup screenshots in README
  README.md
  art/screen-1.png
  art/screen-2.png
  art/screen-3.png
  art/screen-4.png
  art/screen-5.png
  art/screen-6.png
  art/screen-7.png
  art/screen-8.png
  art/screen-9.png
Labels: PR: unreviewed

#134 [QBIT-37] Add deeplink support
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/dev/yashgarg/qbit/MainActivity.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerFragment.kt
Labels: enhancement, PR: reviewed-approved, hacktoberfest-accepted

#117 [QBIT-33] Add ServerPreferences implementation with DataStore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/dev/yashgarg/qbit/MainActivity.kt
  app/src/main/kotlin/dev/yashgarg/qbit/data/models/ServerPreferences.kt
  app/src/main/kotlin/dev/yashgarg/qbit/data/preferences/ServerPreferencesSerializer.kt
  app/src/main/kotlin/dev/yashgarg/qbit/di/AppModule.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/config/ConfigFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/dialogs/AddTorrentDialog.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/TorrentDetailsFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/TorrentDetailsViewModel.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/torrent/tabs/TorrentPeersFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/validation/PortValidator.kt
  app/src/main/res/layout/server_fragment.xml
  app/src/main/res/layout/torrent_details_fragment.xml
  app/src/main/res/layout/tracker_item.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: PR: unreviewed

#145 fix: handle intent after qbit client loaded
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerFragment.kt
  app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModel.kt
Labels: PR: reviewed-approved
